#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$ROOT_DIR/src/utils.sh"

PROJECT_DIR="${1:-$(pwd)}"
GAME_NAME="${GAME_NAME:-my-game}"
BUILD_DIR="${BUILD_DIR:-builds}"
OUTPUT_DIR="${BUILD_DIR}/linux"

build_linux(){
    print_header "BUILDING FOR LINUX"
    cd "$PROJECT_DIR" || exit 1

    if [ "$GAME_NAME" = "my-game" ] && [ -f "conf.lua" ]; then
        detected=$(detect_project_config 2>/dev/null || echo "|")
        detecded_name=$(echo "$detected" |  cut -d'|' -f1)
        if [ -n "$detected_name" ]; then
            GAME_NAME="$detected_name"
            print_info "Detected game name: $GAME_NAME"
        fi
    fi

    if [ ! -f "main.lua" ]; then
        print_warning "main.lua not found in $PROJECT_DIR"
    fi

    if [ ! -f "conf.lua" ]; then
        print_warning "conf.lua not found in $PROJECT_DIR"
    fi

    if ! command -v zip &> /dev/null; then
        print_error "zip command not found. Install it with: sudo apt install zip"
        return 1
    fi

    mkdir -p "$PROJECT_DIR/$OUTPUT_DIR"
    ABS_OUTPUT_DIR="$(cd "$PROJECT_DIR/$OUTPUT_DIR" && pwd)"
    
    print_info "Creating build directory: $ABS_OUTPUT_DIR"
    print_info "Current directory: $(pwd)"

    BUILD_TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
    BUILD_UUID=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen 2>/dev/null || echo "$(date +%s)$$")
    BUILD_ID="${BUILD_TIMESTAMP}_${BUILD_UUID:0:8}"
    
    love_file="${GAME_NAME}_${BUILD_ID}.love"
    FULL_LOVE_PATH="$ABS_OUTPUT_DIR/$love_file"
    
    print_info "Creating $love_file..."
    print_info "Full path: $FULL_LOVE_PATH"

    zip -9 -q -r "$FULL_LOVE_PATH" . \
        -x "*.git*" \
        -x "${BUILD_DIR}/*" \
        -x "builds/*" \
        -x "*.md" \
        -x "*.sh" \
        -x "*.txt" \
        -x ".gitignore" \
        -x "src/*" \
        -x "scripts/*"

    if [ ! -f "$FULL_LOVE_PATH" ]; then
        print_error "Failed to create $love_file"
        print_error "Expected path: $FULL_LOVE_PATH"
        return 1
    fi

    file_size=$(stat -c %s "$FULL_LOVE_PATH" 2>/dev/null || echo "unknown")
    file_size_human=$(du -h "$FULL_LOVE_PATH" 2>/dev/null | cut -f1)
    print_success "Build file created successfully!"
    print_info "Location: $FULL_LOVE_PATH"
    print_info "Size: $file_size_human ($file_size bytes)"

    LOG_FILE="$ABS_OUTPUT_DIR/build-history.log"
    print_info "Logging build to: $LOG_FILE"
    
    if [ ! -f "$LOG_FILE" ]; then
        echo "# LÖVE2D Build History Log" > "$LOG_FILE"
        echo "# Generated by love2d-builder-cli" >> "$LOG_FILE"
        echo "# Format: TIMESTAMP | BUILD_ID | GAME_NAME | FILE_SIZE | FILE_PATH" >> "$LOG_FILE"
        echo "# ================================================================================================" >> "$LOG_FILE"
        echo "" >> "$LOG_FILE"
    fi
    
    log_entry="$(date '+%Y-%m-%d %H:%M:%S') | $BUILD_ID | $GAME_NAME | $file_size_human ($file_size bytes) | $love_file"
    echo "$log_entry" >> "$LOG_FILE"
    print_success "Build logged successfully!"

    print_info "Creating launcher script..."
    cat > "$ABS_OUTPUT_DIR/run.sh" << 'LAUNCHER'
#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

show_menu() {
    while true; do
        echo "=================================="
        echo "      LÖVE Game Launcher"
        echo "=================================="
        echo ""
        
        BUILDS=()
        while IFS= read -r -d '' file; do
            BUILDS+=("$(basename "$file")")
        done < <(find "$SCRIPT_DIR" -maxdepth 1 -name "*.love" -type f -print0 2>/dev/null | sort -z)
        
        if [ ${#BUILDS[@]} -eq 0 ]; then
            echo "No builds found in $SCRIPT_DIR"
            exit 1
        fi
        
        echo "Available builds:"
        echo ""
        for i in "${!BUILDS[@]}"; do
            build_name="${BUILDS[$i]}"
            timestamp=$(echo "$build_name" | grep -oP '\d{8}_\d{6}' | head -1)
            if [ -n "$timestamp" ]; then
                formatted_date=$(echo "$timestamp" | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)_\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1-\2-\3 \4:\5:\6/')
                echo "  [$((i+1))] $build_name ($formatted_date)"
            else
                echo "  [$((i+1))] $build_name"
            fi
        done
        
        echo ""
        echo "  [0] Exit"
        echo ""
        read -rp "Select a build to run [1-${#BUILDS[@]}]: " choice
        
        if [ "$choice" = "0" ]; then
            echo "Goodbye!"
            exit 0
        fi
        
        if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le ${#BUILDS[@]} ]; then
            selected="${BUILDS[$((choice-1))]}"
            echo ""
            echo "Launching: $selected"
            love "$SCRIPT_DIR/$selected" "$@"
            break
        else
            echo ""
            echo " Invalid selection. Please try again."
            echo ""
            sleep 1
        fi
    done
}

# If a specific .love file is passed as argument, run it directly
if [ -n "$1" ] && [ -f "$SCRIPT_DIR/$1" ]; then
    love "$SCRIPT_DIR/$1" "${@:2}"
else
    show_menu "$@"
fi
LAUNCHER
    
    chmod +x "$ABS_OUTPUT_DIR/run.sh"

    echo ""
    print_success "Linux build complete!"
    echo ""
    echo "Build ID: $BUILD_ID"
    echo "Output directory: $ABS_OUTPUT_DIR"
    echo ""
    print_info "Refreshing filesystem cache..."
    
    sync
    
    touch "$ABS_OUTPUT_DIR"
    touch "$PROJECT_DIR/$BUILD_DIR"
    
    touch "$ABS_OUTPUT_DIR/.refresh_${BUILD_ID}"
    sleep 0.1
    rm -f "$ABS_OUTPUT_DIR/.refresh_${BUILD_ID}"
    
    find "$ABS_OUTPUT_DIR" -maxdepth 1 -type f > /dev/null 2>&1
    
    echo ""
    print_success "Linux build complete!"
    echo ""
    echo "Build ID: $BUILD_ID"
    echo "Output: $ABS_OUTPUT_DIR/$love_file"
    echo ""
    
    build_count=$(find "$ABS_OUTPUT_DIR" -maxdepth 1 -name "*.love" -type f 2>/dev/null | wc -l)
    print_info "Total builds: $build_count"
    echo ""
    print_warning "If build files don't appear in explorer files, refresh the folder view"
    print_info "Use 'Run Build' option to launch builds"
}

build_linux "$@"